// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	action "SimpleDouYin/app/service/action/api/internal/handler/action"
	"SimpleDouYin/app/service/action/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CORSMiddleware, serverCtx.LimitMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/douyin/favorite/action",
					Handler: action.FavoriteHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/douyin/favorite/list",
					Handler: action.FavoriteListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/douyin/comment/action",
					Handler: action.CommentHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/douyin/comment/list",
					Handler: action.CommentListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/douyin/relation/action",
					Handler: action.FollowHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/douyin/relation/follow/list",
					Handler: action.FollowListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/douyin/relation/follower/list",
					Handler: action.FollowerListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/douyin/relation/friend/list",
					Handler: action.FriendListHandler(serverCtx),
				},
			}...,
		),
	)
}
