// Code generated by goctl. DO NOT EDIT.
// Source: action.proto

package server

import (
	"context"

	"SimpleDouYin/app/service/action/rpc/internal/logic"
	"SimpleDouYin/app/service/action/rpc/internal/svc"
	"SimpleDouYin/app/service/action/rpc/pb"
)

type ActionServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedActionServer
}

func NewActionServer(svcCtx *svc.ServiceContext) *ActionServer {
	return &ActionServer{
		svcCtx: svcCtx,
	}
}

func (s *ActionServer) Favorite(ctx context.Context, in *pb.FavoriteReq) (*pb.FavoriteResp, error) {
	l := logic.NewFavoriteLogic(ctx, s.svcCtx)
	return l.Favorite(in)
}

func (s *ActionServer) FavoriteList(ctx context.Context, in *pb.FavoriteListReq) (*pb.FavoriteListResp, error) {
	l := logic.NewFavoriteListLogic(ctx, s.svcCtx)
	return l.FavoriteList(in)
}

func (s *ActionServer) Comment(ctx context.Context, in *pb.CommentReq) (*pb.CommentResp, error) {
	l := logic.NewCommentLogic(ctx, s.svcCtx)
	return l.Comment(in)
}

func (s *ActionServer) CommentList(ctx context.Context, in *pb.CommentListReq) (*pb.CommentListResp, error) {
	l := logic.NewCommentListLogic(ctx, s.svcCtx)
	return l.CommentList(in)
}
