// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"SimpleDouYin/app/service/user/dao/model"
)

func newUserFollow(db *gorm.DB) userFollow {
	_userFollow := userFollow{}

	_userFollow.userFollowDo.UseDB(db)
	_userFollow.userFollowDo.UseModel(&model.UserFollow{})

	tableName := _userFollow.userFollowDo.TableName()
	_userFollow.ALL = field.NewAsterisk(tableName)

	_userFollow.fillFieldMap()

	return _userFollow
}

type userFollow struct {
	userFollowDo userFollowDo

	ALL field.Asterisk

	fieldMap map[string]field.Expr
}

func (u userFollow) Table(newTableName string) *userFollow {
	u.userFollowDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userFollow) As(alias string) *userFollow {
	u.userFollowDo.DO = *(u.userFollowDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userFollow) updateTableName(table string) *userFollow {
	u.ALL = field.NewAsterisk(table)

	u.fillFieldMap()

	return u
}

func (u *userFollow) WithContext(ctx context.Context) *userFollowDo {
	return u.userFollowDo.WithContext(ctx)
}

func (u userFollow) TableName() string { return u.userFollowDo.TableName() }

func (u userFollow) Alias() string { return u.userFollowDo.Alias() }

func (u *userFollow) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userFollow) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 0)
}

func (u userFollow) clone(db *gorm.DB) userFollow {
	u.userFollowDo.ReplaceDB(db)
	return u
}

type userFollowDo struct{ gen.DO }

func (u userFollowDo) Debug() *userFollowDo {
	return u.withDO(u.DO.Debug())
}

func (u userFollowDo) WithContext(ctx context.Context) *userFollowDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userFollowDo) ReadDB() *userFollowDo {
	return u.Clauses(dbresolver.Read)
}

func (u userFollowDo) WriteDB() *userFollowDo {
	return u.Clauses(dbresolver.Write)
}

func (u userFollowDo) Clauses(conds ...clause.Expression) *userFollowDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userFollowDo) Returning(value interface{}, columns ...string) *userFollowDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userFollowDo) Not(conds ...gen.Condition) *userFollowDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userFollowDo) Or(conds ...gen.Condition) *userFollowDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userFollowDo) Select(conds ...field.Expr) *userFollowDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userFollowDo) Where(conds ...gen.Condition) *userFollowDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userFollowDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *userFollowDo {
	return u.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (u userFollowDo) Order(conds ...field.Expr) *userFollowDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userFollowDo) Distinct(cols ...field.Expr) *userFollowDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userFollowDo) Omit(cols ...field.Expr) *userFollowDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userFollowDo) Join(table schema.Tabler, on ...field.Expr) *userFollowDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userFollowDo) LeftJoin(table schema.Tabler, on ...field.Expr) *userFollowDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userFollowDo) RightJoin(table schema.Tabler, on ...field.Expr) *userFollowDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userFollowDo) Group(cols ...field.Expr) *userFollowDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userFollowDo) Having(conds ...gen.Condition) *userFollowDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userFollowDo) Limit(limit int) *userFollowDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userFollowDo) Offset(offset int) *userFollowDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userFollowDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *userFollowDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userFollowDo) Unscoped() *userFollowDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userFollowDo) Create(values ...*model.UserFollow) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userFollowDo) CreateInBatches(values []*model.UserFollow, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userFollowDo) Save(values ...*model.UserFollow) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userFollowDo) First() (*model.UserFollow, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserFollow), nil
	}
}

func (u userFollowDo) Take() (*model.UserFollow, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserFollow), nil
	}
}

func (u userFollowDo) Last() (*model.UserFollow, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserFollow), nil
	}
}

func (u userFollowDo) Find() ([]*model.UserFollow, error) {
	result, err := u.DO.Find()
	return result.([]*model.UserFollow), err
}

func (u userFollowDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserFollow, err error) {
	buf := make([]*model.UserFollow, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userFollowDo) FindInBatches(result *[]*model.UserFollow, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userFollowDo) Attrs(attrs ...field.AssignExpr) *userFollowDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userFollowDo) Assign(attrs ...field.AssignExpr) *userFollowDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userFollowDo) Joins(fields ...field.RelationField) *userFollowDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userFollowDo) Preload(fields ...field.RelationField) *userFollowDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userFollowDo) FirstOrInit() (*model.UserFollow, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserFollow), nil
	}
}

func (u userFollowDo) FirstOrCreate() (*model.UserFollow, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserFollow), nil
	}
}

func (u userFollowDo) FindByPage(offset int, limit int) (result []*model.UserFollow, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userFollowDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userFollowDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userFollowDo) Delete(models ...*model.UserFollow) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userFollowDo) withDO(do gen.Dao) *userFollowDo {
	u.DO = *do.(*gen.DO)
	return u
}
