// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	video "SimpleDouYin/app/service/video/api/internal/handler/video"
	"SimpleDouYin/app/service/video/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CORSMiddleware, serverCtx.LimitMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/douyin/feed",
					Handler: video.FeedHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/douyin/publish/action",
					Handler: video.PublishHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/douyin/publish/list",
					Handler: video.PublishListHandler(serverCtx),
				},
			}...,
		),
	)
}
