// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"SimpleDouYin/app/service/video/dao/model"
)

func newVideoPublish(db *gorm.DB) videoPublish {
	_videoPublish := videoPublish{}

	_videoPublish.videoPublishDo.UseDB(db)
	_videoPublish.videoPublishDo.UseModel(&model.VideoPublish{})

	tableName := _videoPublish.videoPublishDo.TableName()
	_videoPublish.ALL = field.NewAsterisk(tableName)

	_videoPublish.fillFieldMap()

	return _videoPublish
}

type videoPublish struct {
	videoPublishDo videoPublishDo

	ALL field.Asterisk

	fieldMap map[string]field.Expr
}

func (v videoPublish) Table(newTableName string) *videoPublish {
	v.videoPublishDo.UseTable(newTableName)
	return v.updateTableName(newTableName)
}

func (v videoPublish) As(alias string) *videoPublish {
	v.videoPublishDo.DO = *(v.videoPublishDo.As(alias).(*gen.DO))
	return v.updateTableName(alias)
}

func (v *videoPublish) updateTableName(table string) *videoPublish {
	v.ALL = field.NewAsterisk(table)

	v.fillFieldMap()

	return v
}

func (v *videoPublish) WithContext(ctx context.Context) *videoPublishDo {
	return v.videoPublishDo.WithContext(ctx)
}

func (v videoPublish) TableName() string { return v.videoPublishDo.TableName() }

func (v videoPublish) Alias() string { return v.videoPublishDo.Alias() }

func (v *videoPublish) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := v.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (v *videoPublish) fillFieldMap() {
	v.fieldMap = make(map[string]field.Expr, 0)
}

func (v videoPublish) clone(db *gorm.DB) videoPublish {
	v.videoPublishDo.ReplaceDB(db)
	return v
}

type videoPublishDo struct{ gen.DO }

func (v videoPublishDo) Debug() *videoPublishDo {
	return v.withDO(v.DO.Debug())
}

func (v videoPublishDo) WithContext(ctx context.Context) *videoPublishDo {
	return v.withDO(v.DO.WithContext(ctx))
}

func (v videoPublishDo) ReadDB() *videoPublishDo {
	return v.Clauses(dbresolver.Read)
}

func (v videoPublishDo) WriteDB() *videoPublishDo {
	return v.Clauses(dbresolver.Write)
}

func (v videoPublishDo) Clauses(conds ...clause.Expression) *videoPublishDo {
	return v.withDO(v.DO.Clauses(conds...))
}

func (v videoPublishDo) Returning(value interface{}, columns ...string) *videoPublishDo {
	return v.withDO(v.DO.Returning(value, columns...))
}

func (v videoPublishDo) Not(conds ...gen.Condition) *videoPublishDo {
	return v.withDO(v.DO.Not(conds...))
}

func (v videoPublishDo) Or(conds ...gen.Condition) *videoPublishDo {
	return v.withDO(v.DO.Or(conds...))
}

func (v videoPublishDo) Select(conds ...field.Expr) *videoPublishDo {
	return v.withDO(v.DO.Select(conds...))
}

func (v videoPublishDo) Where(conds ...gen.Condition) *videoPublishDo {
	return v.withDO(v.DO.Where(conds...))
}

func (v videoPublishDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *videoPublishDo {
	return v.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (v videoPublishDo) Order(conds ...field.Expr) *videoPublishDo {
	return v.withDO(v.DO.Order(conds...))
}

func (v videoPublishDo) Distinct(cols ...field.Expr) *videoPublishDo {
	return v.withDO(v.DO.Distinct(cols...))
}

func (v videoPublishDo) Omit(cols ...field.Expr) *videoPublishDo {
	return v.withDO(v.DO.Omit(cols...))
}

func (v videoPublishDo) Join(table schema.Tabler, on ...field.Expr) *videoPublishDo {
	return v.withDO(v.DO.Join(table, on...))
}

func (v videoPublishDo) LeftJoin(table schema.Tabler, on ...field.Expr) *videoPublishDo {
	return v.withDO(v.DO.LeftJoin(table, on...))
}

func (v videoPublishDo) RightJoin(table schema.Tabler, on ...field.Expr) *videoPublishDo {
	return v.withDO(v.DO.RightJoin(table, on...))
}

func (v videoPublishDo) Group(cols ...field.Expr) *videoPublishDo {
	return v.withDO(v.DO.Group(cols...))
}

func (v videoPublishDo) Having(conds ...gen.Condition) *videoPublishDo {
	return v.withDO(v.DO.Having(conds...))
}

func (v videoPublishDo) Limit(limit int) *videoPublishDo {
	return v.withDO(v.DO.Limit(limit))
}

func (v videoPublishDo) Offset(offset int) *videoPublishDo {
	return v.withDO(v.DO.Offset(offset))
}

func (v videoPublishDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *videoPublishDo {
	return v.withDO(v.DO.Scopes(funcs...))
}

func (v videoPublishDo) Unscoped() *videoPublishDo {
	return v.withDO(v.DO.Unscoped())
}

func (v videoPublishDo) Create(values ...*model.VideoPublish) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Create(values)
}

func (v videoPublishDo) CreateInBatches(values []*model.VideoPublish, batchSize int) error {
	return v.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (v videoPublishDo) Save(values ...*model.VideoPublish) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Save(values)
}

func (v videoPublishDo) First() (*model.VideoPublish, error) {
	if result, err := v.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.VideoPublish), nil
	}
}

func (v videoPublishDo) Take() (*model.VideoPublish, error) {
	if result, err := v.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.VideoPublish), nil
	}
}

func (v videoPublishDo) Last() (*model.VideoPublish, error) {
	if result, err := v.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.VideoPublish), nil
	}
}

func (v videoPublishDo) Find() ([]*model.VideoPublish, error) {
	result, err := v.DO.Find()
	return result.([]*model.VideoPublish), err
}

func (v videoPublishDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.VideoPublish, err error) {
	buf := make([]*model.VideoPublish, 0, batchSize)
	err = v.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (v videoPublishDo) FindInBatches(result *[]*model.VideoPublish, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return v.DO.FindInBatches(result, batchSize, fc)
}

func (v videoPublishDo) Attrs(attrs ...field.AssignExpr) *videoPublishDo {
	return v.withDO(v.DO.Attrs(attrs...))
}

func (v videoPublishDo) Assign(attrs ...field.AssignExpr) *videoPublishDo {
	return v.withDO(v.DO.Assign(attrs...))
}

func (v videoPublishDo) Joins(fields ...field.RelationField) *videoPublishDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Joins(_f))
	}
	return &v
}

func (v videoPublishDo) Preload(fields ...field.RelationField) *videoPublishDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Preload(_f))
	}
	return &v
}

func (v videoPublishDo) FirstOrInit() (*model.VideoPublish, error) {
	if result, err := v.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.VideoPublish), nil
	}
}

func (v videoPublishDo) FirstOrCreate() (*model.VideoPublish, error) {
	if result, err := v.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.VideoPublish), nil
	}
}

func (v videoPublishDo) FindByPage(offset int, limit int) (result []*model.VideoPublish, count int64, err error) {
	result, err = v.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = v.Offset(-1).Limit(-1).Count()
	return
}

func (v videoPublishDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = v.Count()
	if err != nil {
		return
	}

	err = v.Offset(offset).Limit(limit).Scan(result)
	return
}

func (v videoPublishDo) Scan(result interface{}) (err error) {
	return v.DO.Scan(result)
}

func (v videoPublishDo) Delete(models ...*model.VideoPublish) (result gen.ResultInfo, err error) {
	return v.DO.Delete(models)
}

func (v *videoPublishDo) withDO(do gen.Dao) *videoPublishDo {
	v.DO = *do.(*gen.DO)
	return v
}
