// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	lg "go-zero-demo/app/service/user/api/internal/handler/lg"
	token "go-zero-demo/app/service/user/api/internal/handler/token"
	"go-zero-demo/app/service/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/sendvcode",
				Handler: lg.SendVCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: lg.UserRegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: lg.UserLoginHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWT},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/user/refreshtk",
					Handler: token.RefreshTokenHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/user/getuserinfo",
					Handler: token.GetUserInfoHandler(serverCtx),
				},
			}...,
		),
	)
}
