// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package user

import (
	"context"

	"SimpleDouYin/app/service/user/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetInfoReps = pb.GetInfoReps
	GetInfoReq  = pb.GetInfoReq
	LoginReps   = pb.LoginReps
	LoginReq    = pb.LoginReq
	RegisterReq = pb.RegisterReq
	RegisterRes = pb.RegisterRes
	UserInfo    = pb.UserInfo

	User interface {
		Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterRes, error)
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginReps, error)
		GetInfo(ctx context.Context, in *GetInfoReq, opts ...grpc.CallOption) (*GetInfoReps, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterRes, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultUser) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginReps, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultUser) GetInfo(ctx context.Context, in *GetInfoReq, opts ...grpc.CallOption) (*GetInfoReps, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.GetInfo(ctx, in, opts...)
}
