// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameVideo = "video"

// Video mapped from table <video>
type Video struct {
	VideoID       int64  `gorm:"column:video_id;primaryKey" json:"video_id"`           // video唯一标识
	PlayURL       string `gorm:"column:play_url;not null" json:"play_url"`             // 播放地址
	CoverURL      string `gorm:"column:cover_url;not null" json:"cover_url"`           // 封面地址
	FavoriteCount int64  `gorm:"column:favorite_count;not null" json:"favorite_count"` // 点赞数
	CommentCount  int64  `gorm:"column:comment_count;not null" json:"comment_count"`   // 评论数
	Hash          string `gorm:"column:hash;not null" json:"hash"`                     // 哈希值
}

// TableName Video's table name
func (*Video) TableName() string {
	return TableNameVideo
}
