// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameVideoPublish = "video publish"

// VideoPublish mapped from table <video publish>
type VideoPublish struct {
}

// TableName VideoPublish's table name
func (*VideoPublish) TableName() string {
	return TableNameVideoPublish
}
