// Code generated by goctl. DO NOT EDIT.
package types

type RegisterRequest struct {
	UserTrueName string `json:"userTrueName"`
	UserNickName string `json:"userNickName"`
	Sex          string `json:"sex"`
	UserSchool   string `json:"userSchool"`
	UserStno     string `json:"userStno"`
	UserRole     string `json:"userRole"`
	UserPnum     string `json:"userPnum"`
	UserPassword string `json:"userPassword"`
	VCode        string `json:"vCode"`
}

type RegisterResponse struct {
	Status int    `json:"status"`
	Info   string `json:"info"`
}

type SendVCodeRequest struct {
	PhoneNumber string `json:"phoneNumber"`
}

type SendVCodeResponse struct {
	Status int    `json:"status"`
	Info   string `json:"info"`
}

type LoginRequest struct {
	UserPnum     string `json:"userPnum"`
	UserPassword string `json:"userPassword"`
}

type LoginResponse struct {
	Status       int    `json:"status"`
	Info         string `json:"info"`
	AccessToken  string `json:"accessToken"`
	AccessExpire int    `json:"accessExpire"`
	RefreshToken string `json:"refreshToken"`
	UserRole     string `json:"userRole"`
}

type RefreshTokenResponse struct {
	Status       int    `json:"status"`
	Info         string `json:"info"`
	AccessToken  string `json:"accessToken"`
	AccessExpire int    `json:"accessExpire"`
}

type GetUserInfoResponse struct {
	Status       int    `json:"status"`
	Info         string `json:"info"`
	UserTrueName string `json:"userTrueName"`
	UserNickName string `json:"userNickName"`
	Sex          string `json:"sex"`
	UserSchool   string `json:"userSchool"`
	UserStno     string `json:"userStno"`
	UserRole     string `json:"userRole"`
	UserPnum     string `json:"userPnum"`
	UserPassword string `json:"-"`
}
