// Code generated by goctl. DO NOT EDIT.
package types

type RegisterRequest struct {
	UserName string `json:"username"`
	PassWord string `json:"password"`
}

type RegisterResponse struct {
	StatusCode int32  `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
	UserId     int64  `json:"user_id"`
	Token      string `json:"token"`
}

type LoginRequest struct {
	UserName string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	StatusCode int32  `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
	UserId     int64  `json:"user_id"`
	Token      string `json:"token"`
}

type GetUserInfoRequest struct {
	UserId int64  `json:"user_id"`
	Token  string `json:"token"`
}

type GetUserInfoResponse struct {
	StatusCode int32  `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
}
