// Code generated by goctl. DO NOT EDIT.
package types

type SendMsgReq struct {
	Token      string `form:"token"`
	ToUserId   string `form:"to_user_id"`
	ActionType string `form:"action_type"`
	Content    string `form:"content"`
}

type SendMsgResp struct {
	StatusCode int32  `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
}

type MsgRecordReq struct {
	Token    string `form:"token"`
	ToUserId string `form:"to_user_id"`
}

type MsgRecordResp struct {
	StatusCode string    `json:"status_code"`
	StatusMsg  string    `json:"status_msg"`
	MsgList    []Message `json:"message_list"`
}

type Message struct {
	Id         int64  `json:"id"`
	Content    string `json:"content"`
	CreateTime string `json:"create_time"`
}
