// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePublish = "publish"

// Publish mapped from table <publish>
type Publish struct {
	Title       string `gorm:"column:title;not null" json:"title"`               // 标题
	PublishTime int64  `gorm:"column:publish_time;not null" json:"publish_time"` // 时间戳 unix
	UserID      int64  `gorm:"column:user_id;not null" json:"user_id"`           // 用户id
	VideoID     int64  `gorm:"column:video_id;not null" json:"video_id"`         // 视频id
}

// TableName Publish's table name
func (*Publish) TableName() string {
	return TableNamePublish
}
