// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"go-zero-demo/app/service/user/rpc/internal/logic"
	"go-zero-demo/app/service/user/rpc/internal/svc"
	"go-zero-demo/app/service/user/rpc/pb"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Register(ctx context.Context, in *pb.RegisterReq) (*pb.RegisterRes, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServer) SendVCode(ctx context.Context, in *pb.SendVCodeReq) (*pb.SendVCodeRes, error) {
	l := logic.NewSendVCodeLogic(ctx, s.svcCtx)
	return l.SendVCode(in)
}

func (s *UserServer) Login(ctx context.Context, in *pb.LoginReq) (*pb.LoginReps, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServer) GetInfoByPnum(ctx context.Context, in *pb.GetInfoByPnumReq) (*pb.GetInfoByPnumReps, error) {
	l := logic.NewGetInfoByPnumLogic(ctx, s.svcCtx)
	return l.GetInfoByPnum(in)
}
