// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	UserTrueName string    `gorm:"column:user_true_name;not null" json:"user_true_name"`              // 用户真名
	UserNickName string    `gorm:"column:user_nick_name;not null;default:user" json:"user_nick_name"` // 昵称
	Sex          string    `gorm:"column:sex" json:"sex"`                                             // 性别
	UserSchool   string    `gorm:"column:user_school;not null" json:"user_school"`                    // 学校名
	UserStno     string    `gorm:"column:user_stno" json:"user_stno"`                                 // 学工号
	UserRole     string    `gorm:"column:user_role;not null" json:"user_role"`                        // 身份: 教师或学生
	UserPnum     string    `gorm:"column:user_pnum;primaryKey" json:"user_pnum"`                      // 手机号
	UserPassword string    `gorm:"column:user_password;not null" json:"user_password"`                // 用户密码
	CreatTime    time.Time `gorm:"column:creatTime" json:"creatTime"`                                 // 创建时间
	UpdateTime   time.Time `gorm:"column:updateTime" json:"updateTime"`                               // 修改时间
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
