// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserFollow = "user follow"

// UserFollow mapped from table <user follow>
type UserFollow struct {
}

// TableName UserFollow's table name
func (*UserFollow) TableName() string {
	return TableNameUserFollow
}
