// Code generated by goctl. DO NOT EDIT.
package types

type FavoriteReq struct {
	Token      string `form:"token"`
	VideoId    string `form:"video_id"`
	ActionType string `form:"action_type"`
}

type FavoriteResp struct {
	StatusCode int32  `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
}

type FavoriteListReq struct {
	UserId string `form:"user_id"`
	Token  string `form:"token"`
}

type FavoriteListResp struct {
	StatusCode string  `json:"status_code"`
	StatusMsg  string  `json:"status_msg"`
	VideoList  []Video `json:"video_list"`
}

type Video struct {
	Id            int64  `json:"id"`
	Author        Author `json:"author"`
	PlayUrl       string `json:"play_url"`
	CoverUrl      string `json:"cover_url"`
	FavoriteCount int64  `json:"favorite_count"`
	CommentCount  int64  `json:"comment_count"`
	IsFavorite    bool   `json:"is_favorite"`
	Title         string `json:"title"`
}

type Author struct {
	Id            int64  `json:"id"`
	Name          string `json:"name"`
	FollowCount   int64  `json:"follow_count"`
	FollowerCount int64  `json:"follower_count"`
	IsFollow      bool   `json:"is_follow"`
}

type CommentReq struct {
	Token       string `form:"token"`
	VideoId     string `form:"video_id"`
	ActionType  string `form:"action_type"`
	CommentText string `form:"comment_text,optional"`
	CommentId   string `form:"comment_id,optional"`
}

type CommentResp struct {
	StatusCode int32   `json:"status_code"`
	StatusMsg  string  `json:"status_msg"`
	Comment    Comment `json:"comment"`
}

type Comment struct {
	Id         int64  `json:"id"`
	User       Author `json:"user"`
	Content    string `json:"content"`
	CreateDate string `json:"create_date"`
}

type CommentListReq struct {
	Token   string `form:"token"`
	VideoId string `form:"video_id"`
}

type CommentListResp struct {
	StatusCode  int32     `json:"status_code"`
	StatusMsg   string    `json:"status_msg"`
	CommentList []Comment `json:"comment_list"`
}

type FollowReq struct {
	Token      string `form:"token""`
	ToUserId   string `form:"to_user_id"`
	ActionType string `form:"action_type"`
}

type FollowResp struct {
	StatusCode int32  `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
}

type FollowListReq struct {
	Token  string `form:"token""`
	UserID string `form:"user_id"`
}

type FollowListResp struct {
	StatusCode string   `json:"status_code"`
	StatusMsg  string   `json:"status_msg"`
	UserList   []Author `json:"user_list"`
}

type FollowerListReq struct {
	Token  string `form:"token""`
	UserID string `form:"user_id"`
}

type FollowerListResp struct {
	StatusCode string   `json:"status_code"`
	StatusMsg  string   `json:"status_msg"`
	UserList   []Author `json:"user_list"`
}

type FriendListReq struct {
	Token  string `form:"token""`
	UserID string `form:"user_id"`
}

type FriendListResp struct {
	StatusCode string   `json:"status_code"`
	StatusMsg  string   `json:"status_msg"`
	UserList   []Author `json:"user_list"`
}
