// Code generated by goctl. DO NOT EDIT.
// Source: action.proto

package action

import (
	"context"

	"SimpleDouYin/app/service/action/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Author           = pb.Author
	Comment          = pb.Comment
	CommentListReq   = pb.CommentListReq
	CommentListResp  = pb.CommentListResp
	CommentReq       = pb.CommentReq
	CommentResp      = pb.CommentResp
	FavoriteListReq  = pb.FavoriteListReq
	FavoriteListResp = pb.FavoriteListResp
	FavoriteReq      = pb.FavoriteReq
	FavoriteResp     = pb.FavoriteResp
	Video            = pb.Video

	Action interface {
		Favorite(ctx context.Context, in *FavoriteReq, opts ...grpc.CallOption) (*FavoriteResp, error)
		FavoriteList(ctx context.Context, in *FavoriteListReq, opts ...grpc.CallOption) (*FavoriteListResp, error)
		Comment(ctx context.Context, in *CommentReq, opts ...grpc.CallOption) (*CommentResp, error)
		CommentList(ctx context.Context, in *CommentListReq, opts ...grpc.CallOption) (*CommentListResp, error)
	}

	defaultAction struct {
		cli zrpc.Client
	}
)

func NewAction(cli zrpc.Client) Action {
	return &defaultAction{
		cli: cli,
	}
}

func (m *defaultAction) Favorite(ctx context.Context, in *FavoriteReq, opts ...grpc.CallOption) (*FavoriteResp, error) {
	client := pb.NewActionClient(m.cli.Conn())
	return client.Favorite(ctx, in, opts...)
}

func (m *defaultAction) FavoriteList(ctx context.Context, in *FavoriteListReq, opts ...grpc.CallOption) (*FavoriteListResp, error) {
	client := pb.NewActionClient(m.cli.Conn())
	return client.FavoriteList(ctx, in, opts...)
}

func (m *defaultAction) Comment(ctx context.Context, in *CommentReq, opts ...grpc.CallOption) (*CommentResp, error) {
	client := pb.NewActionClient(m.cli.Conn())
	return client.Comment(ctx, in, opts...)
}

func (m *defaultAction) CommentList(ctx context.Context, in *CommentListReq, opts ...grpc.CallOption) (*CommentListResp, error) {
	client := pb.NewActionClient(m.cli.Conn())
	return client.CommentList(ctx, in, opts...)
}
