// Code generated by goctl. DO NOT EDIT.
// Source: video.proto

package videosv

import (
	"context"

	"SimpleDouYin/app/service/video/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Author          = pb.Author
	FeedReq         = pb.FeedReq
	FeedResp        = pb.FeedResp
	PublishListReq  = pb.PublishListReq
	PublishListResp = pb.PublishListResp
	PublishReq      = pb.PublishReq
	PublishResp     = pb.PublishResp
	Video           = pb.Video

	VideoSv interface {
		Feed(ctx context.Context, in *FeedReq, opts ...grpc.CallOption) (*FeedResp, error)
		Publish(ctx context.Context, in *PublishReq, opts ...grpc.CallOption) (*PublishResp, error)
		PublishList(ctx context.Context, in *PublishListReq, opts ...grpc.CallOption) (*PublishListResp, error)
	}

	defaultVideoSv struct {
		cli zrpc.Client
	}
)

func NewVideoSv(cli zrpc.Client) VideoSv {
	return &defaultVideoSv{
		cli: cli,
	}
}

func (m *defaultVideoSv) Feed(ctx context.Context, in *FeedReq, opts ...grpc.CallOption) (*FeedResp, error) {
	client := pb.NewVideoSvClient(m.cli.Conn())
	return client.Feed(ctx, in, opts...)
}

func (m *defaultVideoSv) Publish(ctx context.Context, in *PublishReq, opts ...grpc.CallOption) (*PublishResp, error) {
	client := pb.NewVideoSvClient(m.cli.Conn())
	return client.Publish(ctx, in, opts...)
}

func (m *defaultVideoSv) PublishList(ctx context.Context, in *PublishListReq, opts ...grpc.CallOption) (*PublishListResp, error) {
	client := pb.NewVideoSvClient(m.cli.Conn())
	return client.PublishList(ctx, in, opts...)
}
